# Generated by Django 5.1.6 on 2025-03-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionslisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslisting',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('S', 'Sold')], default='A', max_length=1),
        ),
    ]
