# Generated by Django 5.1.6 on 2025-03-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionslisting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bids',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionslisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auctionslisting',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
