# Generated by Django 5.1.6 on 2025-03-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at']},
        ),
    ]
