# Generated by Django 5.1.6 on 2025-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.URLField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
