# Generated by Django 5.1.6 on 2025-03-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_urls_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionslisting',
            options={'ordering': ['created_at']},
        ),
    ]
