# Generated by Django 5.1.6 on 2025-03-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionslisting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='auctions.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
