# Generated by Django 5.1.6 on 2025-03-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comments_parent_comment_alter_comments_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionslisting',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctionslisting'),
        ),
    ]
