# Generated by Django 5.1.6 on 2025-03-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_comment',
            field=models.CharField(max_length=500),
        ),
    ]
