# Generated by Django 5.1.6 on 2025-03-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_watchlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auctionlisting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to='auctions.auctionslisting'),
        ),
    ]
