# Generated by Django 5.1.6 on 2025-03-24 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_watchlist_auctionlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncategories',
            name='category',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auctionslisting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='auctions.auctioncategories'),
        ),
        migrations.AlterField(
            model_name='auctionslisting',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='auctions.descriptions'),
        ),
        migrations.AlterField(
            model_name='auctionslisting',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='auctions.titles'),
        ),
        migrations.AlterField(
            model_name='auctionslisting',
            name='url',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='auctions.urls'),
        ),
    ]
